name: Lint Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: Run Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # キャッシュの読み込み
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # Ruffの実行
      - name: Lint with Ruff
        run: |
          ruff check . --output-format=github
          
      - name: Format check with Ruff
        run: |
          ruff format --check .