
name: Pulumi Up

on:
  push:
    branches:
      - main
      - dev

jobs:
  update:
    name: Pulumi Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run Pulumi Up for main branch
      - uses: pulumi/actions@v6
        if: github.ref == 'refs/heads/main'
        with:
          command: up
          stack-name: ryosukehata/UsecaseAnalyst/main
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DATAROBOT_API_TOKEN: ${{ secrets.DATAROBOT_API_TOKEN }}
          DATAROBOT_ENDPOINT: ${{ secrets.DATAROBOT_ENDPOINT }}
          MULTISTEP: ${{ secrets.MULTISTEP }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
          OPENAI_API_DEPLOYMENT_ID: ${{ secrets.OPENAI_API_DEPLOYMENT_ID }}

      # Run Pulumi Up for dev branch
      - uses: pulumi/actions@v6
        if: github.ref == 'refs/heads/dev'
        with:
          command: up
          stack-name: ryosukehata/UsecaseAnalyst/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DATAROBOT_API_TOKEN: ${{ secrets.DATAROBOT_API_TOKEN }}
          DATAROBOT_ENDPOINT: ${{ secrets.DATAROBOT_ENDPOINT }}
          MULTISTEP: ${{ secrets.MULTISTEP }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
          OPENAI_API_DEPLOYMENT_ID: ${{ secrets.OPENAI_API_DEPLOYMENT_ID }}